### ISSUE TITLE
Feature: Add support for editing Repeater JSON Web Tokens

### ISSUE THREAD

**Issue by philipp-klemmer** [ozzi-/JWT4B#36]
Whenever you send something to Repeater and change the payload, it would be great to adjust the `dta` in the Payload.

**Comment by ozzi-** [comment]
Hi @philipp-klemmer  
can you give me an example? what do you mean by "dta"? 
Cheers

**Comment by philipp-klemmer** [comment]
It would be nice whenever I use the Repeater that it would be possible to also manually adjust the Request Payload inside the JSON Web Tokens tab. Here is a screenshot:
https://i.postimg.cc/Yqrn1L2k/burp-extention.png

**Comment by giovanni-riva** [comment]
Hey @ozzi- , 
nice work first of all!
I think @philipp-klemmer issue more generally is that you cannot edit the parsed JWT in the "Repeater" tab of Burp.

**Comment by ozzi-** [comment]
Hi Guys 
Either build newest commit from source or use the following JAR:
[jwt4b.zip](https://github.com/ozzi-/JWT4B/files/4172169/jwt4b.zip)

The JWT is now editable, but im not sure if the changes are actually sent with the repeated request.
Can you confirm this?

Cheers

**Comment by giovanni-riva** [comment]
Hey @ozzi- 
bug-issue #37 reports the same issue as in this thread.

**Comment by ozzi-** [comment]
I did some testing, nothing done in the JSON Web Tokens tab is actually reflected in the request, when using the repeater. This is due to getMessage (IMessageEditorTab) not being called in JWTInterceptTabController. Ill do some research and come back to you.

**Comment by ozzi-** [comment]
I did some testing, nothing done in the JSON Web Tokens tab is actually reflected in the request, when using the repeater. This is due to getMessage (IMessageEditorTab) not being called in JWTInterceptTabController. Ill do some research and come back to you.

**Comment by ozzi-** [comment]
@giovanni-riva  wanted to delete my duplicate comment, deleted yours, awfully sorry - the UI here is a bit laggy

**Comment by ozzi-** [comment]
getMessage is called in the repeated and returns the correct result. Ill need somebody at PortSwigger Forums to help me out, however they are currently down

**Comment by giovanni-riva** [comment]
Hey @ozzi- , thanks for the updates!
Let's see what PortSwigger replies.

**Comment by ozzi-** [comment]
https://support.portswigger.net/customer/en/portal/questions/17698080-repeater-tab-imessageeditortab-getmessage?new=17698080

**Comment by ozzi-** [comment]
Got a response, Ill cross-check their example implementation with mine. I hope it is easy enough to fix.
```It does not like you are updating the parameter value in the request before it is sent. 

We recommend you look at the sample extensions' implementation of getMessage(). In particular, you should check whether the text is modified, the request is updated with the new parameter value, and the IParameter variable is set correctly. 
```

**Comment by giovanni-riva** [comment]
Awesome, thanks.

**Comment by ozzi-** [comment]
Ok it should work now - sending to repeated, payload "sub" is 1234567890:
![first](https://i.imgur.com/yTvc8wC.png)

Changing it to "sub" to "BLUB" and checking what comes back, it does what is expected:
![first](https://i.imgur.com/U8LouDs.png)

**Comment by giovanni-riva** [comment]
Hey @ozzi- ,
so is the token signature recomputed automatically after changing the payload?
Or do we need to add the secret via GUI (e.g., load secret from file) each time?

**Comment by ozzi-** [comment]
Hi @giovanni-riva  
Oh, that is another problem 😄  I see your point... Let me think

**Comment by ozzi-** [comment]
@giovanni-riva 
I added a config.json switch called "resetEditor". Set it to "false" and the checkbox / radio buttons will stay the same for every request. This defaults to true though, as I fear this will confuse most users, imagine the following:
You are working in the intercept view, first you get a JWT using HS256, so you resign it with the key "abcd", the next request contains a JWT using RS256, it will try to resign it with "abcd" which won't work, since this is not a valid private key. 

Please let me know if this works for you

@philipp-klemmer  I would assume your original issue is fixed already:


Can you guys give me feedback? I attached a freshly built JAR. If all is OK ill do a Pullrequest for portswigger.

[jwt4b.zip](https://github.com/ozzi-/JWT4B/files/4276073/jwt4b.zip)

**Comment by giovanni-riva** [comment]
Hey @ozzi-, thanks for the update.
Will test it by EOW. Thanks

**Comment by giovanni-riva** [comment]
Hi @ozzi- ,
I tested the new version and it seems working for me.
I have a couple of suggestions:

1. Wrap the text inside the jwt editor or add a lateral scrollbar. I couldn't see the whole signature even by enlarging Burp window
2. It may be more user friendly to enable cmd+z to the editor as well
3. It may be more user friendly to enlarge the size of the textfield wer you insert the secret. At the moment I cannot read what I paste inside because the scrollbar covers it.

So far our use case is almost covered. We only have to compute new payloads for each request but this require an md5 of some parameters. I think we will fork your project and add this intermediate step :)

Thanks and keep up the good work!

**Comment by ozzi-** [comment]
Hi @giovanni-riva 
>Wrap the text inside the jwt editor or add a lateral scrollbar. I couldn't see the whole signature even by enlarging Burp window

Scrollbar is now back, I reverted back to rsyntaxtextarea as burp 2020v4 fixed an issue.

>It may be more user friendly to enable cmd+z to the editor as well

This is back too.

>It may be more user friendly to enlarge the size of the textfield wer you insert the secret. At the moment I cannot read what I paste inside because the scrollbar covers it.

Not quite sure,... are you refering to the intercept tab? Recalculate signature?


Feel free to download 1.11, ill create a PR in the mean time to get it into Bapp store.

Cheers

**Comment by giovanni-riva** [comment]
Hey @ozzi- ,
thank you for the updates!

>Not quite sure,... are you refering to the intercept tab? Recalculate signature?

I am referring to the Repeater tab. There is the right section where e.g., you choose the radio button to recalculate the signature. On the bottom you can insert a new signature manually.


>Feel free to download 1.11, ill create a PR in the mean time to get it into Bapp store.

Thanks! Will do

**Comment by ozzi-** [comment]
@giovanni-riva  any feedback on 1.11?

**Comment by ozzi-** [comment]
initial issue is implemented. further improvements please open a new issue, its getting cluttered in here
