### ISSUE TITLE
Rewrite using new Burp Extension API (montoya)

### ISSUE THREAD

**Issue by ozzi-** [ozzi-/JWT4B#87]
https://portswigger.net/burp/documentation/desktop/extensions/creating

**Comment by bcyrill** [comment]
I rewrote the extension using the new Montoya API  😄  https://github.com/bcyrill/JWT4B/tree/montoya

While the majority of changes are conversions of the old to new API calls, the biggest changes logic-wise are within the tokenposition classes.

Regarding the tests, I adapted them as well, but since the Burp specific classes are not available when running tests, had to mock / reimplement quite a bit of Burp internal logic.

In addition, I converted the build system from Maven to Gradle.

**Comment by ozzi-** [comment]
Holy moly, let me have a look as soon as I find some time. Cool stuff

**Comment by ozzi-** [comment]
https://github.com/ozzi-/JWT4B/pull/88 merged into feature branch upstream, will be doing some testing

**Comment by ozzi-** [comment]
There is some small stuff such as removal of custom headers that I will have to reimplement, not all apps use "Authorization Bearer". Also there is a weird bug of JWTs being appended n times when switching between raw and jwt4b in the intercept tab. Otherwise looking good

**Comment by ozzi-** [comment]
@bcyrill FYI - thanks.
Did some tweaks, testing looks good. Will be creating upstream PR to portswigger soon.
![image](https://github.com/ozzi-/JWT4B/assets/7944573/85384b02-fa20-48f7-a0b4-692cd5249645)
