### ISSUE TITLE
Font size of JWT4B fileds does not change using the Burp's settings

### ISSUE THREAD

**Issue by aggressor0** [ozzi-/JWT4B#90]
When changing the font size for Burp tabs and titles, the JWT4B's titles (such as **Enter JWT**, **Decoded JWT**) does not change.

![2024-07-12_18-59](https://github.com/user-attachments/assets/087802cf-953a-45bb-ac66-1401c87efe6b)

**Comment by ozzi-** [comment]
I will have to check Portswiggers documentation on this, thanks!

**Comment by ozzi-** [comment]
![image](https://github.com/user-attachments/assets/6ffca176-a6aa-405d-8892-aaa414de317c)

![image](https://github.com/user-attachments/assets/56c38ad9-8d2f-4577-94dc-5a9992d9fd09)

**Comment by ozzi-** [comment]
fixed with https://github.com/ozzi-/JWT4B/commit/24998d1e5828706f88b132f7a4011a4bd71b85a4

you can get the latest build here - https://github.com/ozzi-/JWT4B/releases/tag/2.6 (or wait for the PR to be accepted by Portswigger)
note: you will have to reload the extension for changes to appear in Intercept & History view, you can do this by:

![image](https://github.com/user-attachments/assets/6bcbdeb3-4cd4-4e63-98bd-912fc20c485e)
